config/routes.rb
Rails.application.routes.draw do
  resources :encounters
  resources :patients
  root 'patients#index'
end

app/models/encounter.rb
class Encounter < ActiveRecord::Base
	belongs_to :patient, :foreign_key => :MRN, :primary_key => "patient_mrn"
	validates :patient_mrn, :visit_number, :admitted_at, presence: true
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_many :encounter, :foreign_key => :patient_mrn, :primary_key => "MRN"
	validates :first_name, :middle_name, presence: true, length: { maximum: 50 }
	validates :MRN, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/encounters_controller.rb
class EncountersController < ApplicationController
  before_action :set_encounter, only: [:show, :edit, :update, :destroy]

  # GET /encounters
  # GET /encounters.json
  def index
    @encounters = Encounter.all
  end

  # GET /encounters/1
  # GET /encounters/1.json
  def show
    @back_url = URI(request.referer || '').path
    if @back_url.nil?
      @back_url = encounters_url
    end
  end

  # GET /encounters/new
  def new
    # TODO: This goes back to Encounters Index, if you make an error in input, then click back. Ask what's the best way of handling this kind of situation
    @back_url = URI(request.referer || '').path
    if @back_url.nil?
      @back_url = encounters_url
    end
    @encounter = Encounter.new
  end

  # GET /encounters/1/edit
  def edit
    @back_url = Patient.find_by(MRN: @encounter.patient_mrn)
    if @back_url.nil?
      @back_url = encounters_url
    end
  end

  # POST /encounters
  # POST /encounters.json
  def create
    @encounter = Encounter.new(encounter_params)
    # Design Choice: When creating new Encounter, go to Patient Show with same MRN as new Encounter
    respond_to do |format|
      if @encounter.save
        @back_url = Patient.find_by(MRN: @encounter.patient_mrn)
        # Need to decide whether or not to Create the Encounter anyways? Might be better to still create it, but remind them that the Patient Isn't found
        if @back_url.nil?
          @back_url = encounters_url
        end

        format.html { redirect_to @back_url, notice: 'Encounter was successfully created.' }
        format.json { render :show, status: :created, location: @back_url }
      else
        format.html { render :new }
        format.json { render json: @encounter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /encounters/1
  # PATCH/PUT /encounters/1.json
  def update
      respond_to do |format|
      @back_url = Patient.find_by(MRN: @encounter.patient_mrn)
      # Upon Editing a record that doesn't have a patient, then return to the Encounters Index
      if @back_url.nil?
        @back_url = encounters_url
      end

      if @encounter.update(encounter_params)
        format.html { redirect_to @back_url, notice: 'Encounter was successfully updated.' }
        format.json { render :show, status: :ok, location: @back_url }
      else
        format.html { render :edit }
        format.json { render json: @encounter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /encounters/1
  # DELETE /encounters/1.json
  def destroy
    @back_url = Patient.find_by(MRN: @encounter.patient_mrn)
    if @back_url.nil?
      @back_url = encounters_url
    end
    @encounter.destroy
    respond_to do |format|
      format.html { redirect_to @back_url, notice: 'Encounter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_encounter
      @encounter = Encounter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def encounter_params
      params.require(:encounter).permit(:patient_mrn, :visit_number, :admitted_at, :discharged_at, :location, :room, :bed)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patients_url, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patients_url, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :middle_name, :last_name, :weight, :height, :MRN)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/encounters_helper.rb
module EncountersHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/encounters/_form.html.erb
<%= bootstrap_form_for(@encounter, layout: :horizontal) do |f| %>
  <% if @encounter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@encounter.errors.count, "error") %> prohibited this encounter from being saved:</h2>

      <ul>
      <% @encounter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :patient_mrn %>
  </div>
  <div class="field">
    <%= f.number_field :visit_number %>
  </div>
  <div class="field">
    <%= f.datetime_select :admitted_at %>
  </div>
  <div class="field">
    <%= f.datetime_select :discharged_at %>
  </div>
  <div class="field">
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.text_field :room %>
  </div>
  <div class="field">
    <%= f.number_field :bed %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-success"%>
  </div>
<% end %>

app/views/encounters/edit.html.erb
<h1>Editing Encounter</h1>

<%= render 'form' %>

<br>
<%= link_to 'Show', @encounter, :class => "btn btn-default" %> |
<%= link_to 'Back', @back_url, :class => "btn btn-default" %>

app/views/encounters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>PatientManager | EncountersList </h1>

<%= link_to 'New Encounter', new_encounter_path, :class => "btn btn-primary" %>

<br><br>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Patient MRN</th>
      <th>Visit number</th>
      <th>Admitted at</th>
      <th>Discharged at</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @encounters.each do |encounter| %>
      <tr>
        <td><%= encounter.patient_mrn %></td>
        <td><%= encounter.visit_number %></td>
        <td><%= encounter.admitted_at %></td>
        <td><%= encounter.discharged_at %></td>
        <td><%= link_to 'Show', encounter, :class => "btn btn-default" %> | 
        <%= link_to 'Edit', edit_encounter_path(encounter), :class => "btn btn-warning" %> | 
        <%= link_to 'Destroy', encounter, :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'PatientsList', patients_url, :class => "btn btn-default" %>

app/views/encounters/new.html.erb
<h1>New Encounter</h1>

<%= render 'form' %>

<br>
<%= link_to 'Back', @back_url, :class => "btn btn-default" %>

app/views/encounters/show.html.erb
<p id="notice"><%= notice %></p>

<h1> Encounter Information </h1>

<table class='table table-bordered'>
  <tbody>

    <tr>
      <td> <strong>Patient MRN:</strong> </td>
      <td> <%= @encounter.patient_mrn %> </td>
    </tr>

    <tr>
      <td> <strong>Visit number:</strong> </td>
      <td> <%= @encounter.visit_number %> </td>
    </tr>

    <tr>
      <td> <strong>Admitted at:</strong> </td>
      <td> <%= @encounter.admitted_at %> </td>
    </tr>

    <tr>
      <td> <strong>Discharged at:</strong> </td>
      <td> <%= @encounter.discharged_at %> </td>
    </tr>

    <tr>
      <td> <strong>Location:</strong> </td>
      <td> <%= @encounter.location %> </td>
    </tr>

    <tr>
      <td> <strong>Room:</strong> </td>
      <td> <%= @encounter.room %> </td>
    </tr>

    <tr>
      <td> <strong>Bed:</strong> </td>
      <td> <%= @encounter.bed %> </td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_encounter_path(@encounter), :class => "btn btn-warning" %> |
<%= link_to 'Back', @back_url, :class => "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PatientManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/patients/_form.html.erb
<%= bootstrap_form_for(@patient, layout: :horizontal) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.text_field :MRN %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-success"%>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form' %>

<br>
<%= link_to 'Show', @patient, :class => "btn btn-default" %> |
<%= link_to 'Back', patients_path, :class => "btn btn-default" %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>PatientManager | PatientsList </h1>

<%= link_to 'New Patient', new_patient_path, :class => "btn btn-primary" %>

<br><br>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>MRN</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.MRN %></td>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= link_to 'Show', patient, :class => "btn btn-default" %> | 
        <%= link_to 'Edit', edit_patient_path(patient), :class => "btn btn-warning" %> | 
        <%= link_to 'Destroy', patient, :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'EncountersList', encounters_url, :class => "btn btn-default" %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path, :class => "btn btn-default" %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<h1> Patient Information </h1>

<table class='table table-bordered'>
  <tbody>

    <tr>
      <td> <strong>First name:</strong> </td>
      <td> <%= @patient.first_name %> </td>
    <tr>

    <tr>
      <td> <strong>Middle name:</strong> </td>
      <td> <%= @patient.middle_name %> </td>
    </tr>

    <tr>
      <td> <strong>Last name:</strong> </td>
      <td> <%= @patient.last_name %> </td>
    </tr>

    <tr>
      <td> <strong>Weight:</strong> </td>
      <td> <%= @patient.weight %> </td>
    </tr>

    <tr>
      <td> <strong>Height:</strong> </td>
      <td> <%= @patient.height %> </td>
    </tr>

    <tr>
      <td> <strong>MRN:</strong> </td>
      <td> <%= @patient.MRN %> </td>
    </tr>

  </tbody>
</table>

<%= link_to 'Edit', edit_patient_path(@patient), :class => "btn btn-warning" %> |
<%= link_to 'Back', patients_path, :class => "btn btn-default" %>

<br>

<h1> Patient Encounters </h1>

<%= link_to 'New Encounter', new_encounter_path, :class => "btn btn-primary" %>
<br><br>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Patient MRN</th>
      <th>Visit number</th>
      <th>Admitted at</th>
      <th>Discharged at</th>
      <th>Actions</th>
    </tr>
  </thead>
<% @patient.encounter.each do |encounter| %> 
  <tr>
        <td><%= encounter.patient_mrn %></td>
        <td><%= encounter.visit_number %></td>
        <td><%= encounter.admitted_at %></td>
        <td><%= encounter.discharged_at %></td>
        <td><%= link_to 'Show', encounter, :class => "btn btn-default" %> | 
        <%= link_to 'Edit', edit_encounter_path(encounter), :class => "btn btn-warning" %> | 
        <%= link_to 'Destroy', encounter, :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
<% end %>
</table>